version: '3.9'

services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=blog
      - POSTGRES_USER=blog
      - POSTGRES_PASSWORD=blog
    restart: "always"
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
  pgadmin:

networks:
  postgres:
    driver: bridge